# Generated by Django 6.0.3 on 2026-03-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
